In [1]:
import pandas as pd

In [38]:
data = pd.read_csv("data/hotel.csv")
data

,Name,Class,Rating,Total Rater,Facility,Price,Area
0,MK HOUSE TENDEAN,2-star hotel,4.4,(548),"['Free Wi-Fi', 'Air conditioning', 'Full-servi...","IDR 113,133",Jakarta
1,RedDoorz @ Cempaka Putih,2-star hotel,4.4,(169),"['Free Wi-Fi', 'Air conditioning', 'Child-frie...","IDR 154,526",Jakarta
2,Green Bamboo Residence,2-star hotel,4.2,"(1,630)","['Breakfast', 'Free Wi-Fi', 'Free parking', 'A...","IDR 159,722",Jakarta
3,RedDoorz Premium @ Cilandak Timur 2,2-star hotel,4.5,(243),"['Free Wi-Fi', 'Outdoor pool']","IDR 184,569",Jakarta
4,Zest Airport Jakarta by Swiss-Belhotel Interna...,2-star hotel,4.2,"(4,237)","['Breakfast', 'Free Wi-Fi', 'Free parking', 'P...","IDR 369,566",Jakarta
...,...,...,...,...,...,...,...
1133,Shangri-La Surabaya,5-star hotel,4.7,"(10,137)","['Breakfast', 'Free Wi-Fi', 'Free parking', 'O...","IDR 1,208,720",Surabaya
1134,Ascott Waterplace Surabaya,5-star hotel,4.6,"(4,224)","['Breakfast', 'Free Wi-Fi', 'Free parking', 'O...","IDR 1,402,300",Surabaya
1135,The Westin Surabaya,5-star hotel,4.8,(949),"['Breakfast ($)', 'Free Wi-Fi', 'Free parking'...","IDR 1,960,200",Surabaya
1136,Bumi Surabaya City Resort,5-star hotel,4.7,"(11,660)","['Free breakfast', 'Free Wi-Fi', 'Free parking...","IDR 690,697",Surabaya
1137,Grand Kebonsari - Guest House & Homestay Syari'ah,5-star hotel,4.5,(227),"['Free Wi-Fi', 'Free parking', 'Air conditioni...","IDR 271,510",Surabaya